'use-strict'

const WRONG_TYPE = "WRONG_TYPE"
const MULTI_TYPE = "MULTI_TYPE"
const NO_NAME = "NO_NAME"
const UPPERCASE = "UPPERCASE"
const INVALID_STYLE = 'INVALID_STYLE'
const PATH_NOT_FOUND = 'PATH_NOT_FOUND'

module.exports = {
  WRONG_TYPE,
  MULTI_TYPE,
  NO_NAME,
  UPPERCASE,
  INVALID_STYLE,
  PATH_NOT_FOUND
}
